-- Index the `rtrim(url)` publication lookup.
--
-- Measured from `pg_stat_statements` over a 9.75-day window on prod (56.8h of
-- total database time). The production compute never suspends — ingest runs
-- 24/7, so `active_time` is ~98.5% of the billing period — which means the bill
-- is CU-seconds and the only lever is CPU per unit of work.
--
--   6.8%  3.88h  rtrim(url) publication lookup   1,782,155 calls @ 7.8ms
--
-- `publications_url_idx` exists on `url`, but every call site wraps the column
-- in `rtrim` to tolerate legacy trailing-slash variants (handlers.ts:134 and
-- :418 on the ingest upsert path, publication-mentions.ts, recompute.ts). That
-- makes the predicate non-sargable, so each of 1.78M calls seq-scans the table.
-- Before:
--
--   Seq Scan on publications  Buffers: shared hit=419
--   Filter: (rtrim(url, '/') = '...')  Rows Removed by Filter: 3572
--
-- and that was a LIMIT 1 that stopped early; a miss scans all 16,741 rows.
-- After, on prod:
--
--   Index Scan using publications_url_normalized_idx  Buffers: shared hit=2 read=1
--
-- 419 buffers to 3, and it fixes all four call sites without code changes.
--
-- Created CONCURRENTLY on prod out-of-band; IF NOT EXISTS makes this a no-op
-- there while still building it on fresh/local/test databases. Same pattern as
-- 0014 and 0003.
CREATE INDEX IF NOT EXISTS "publications_url_normalized_idx" ON "publications" (rtrim("url", '/'));
