/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api/auth/atproto/authorize'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api/auth/atproto/callback'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api/auth/atproto/jwks[.]json'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api/auth/atproto/metadata[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
