/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as ApiResendWebhookRouteImport } from './routes/api.resend-webhook'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as SubscribePubIdRouteImport } from './routes/subscribe.$pubId'
import { Route as SubscribeConfirmRouteImport } from './routes/subscribe.confirm'
import { Route as SubscribeManageRouteImport } from './routes/subscribe.manage'
import { Route as UnsubscribeTokenRouteImport } from './routes/unsubscribe.$token'
import { Route as AppPPubIdRouteImport } from './routes/_app.p.$pubId'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiSubscribersImportRouteImport } from './routes/api/subscribers.import'
import { Route as ApiSubscriptionUnsubscribeRouteImport } from './routes/api/subscription.unsubscribe'
import { Route as AppPPubIdSendPathRouteImport } from './routes/_app.p.$pubId_.$sendPath'
import { Route as AppPPubIdSettingsRouteImport } from './routes/_app.p.$pubId_.settings'
import { Route as ApiAuthAtprotoAuthorizeRouteImport } from './routes/api/auth/atproto/authorize'
import { Route as ApiAuthAtprotoCallbackRouteImport } from './routes/api/auth/atproto/callback'
import { Route as ApiAuthAtprotoJwksDotjsonRouteImport } from './routes/api/auth/atproto/jwks[.]json'
import { Route as ApiAuthAtprotoMetadataDotjsonRouteImport } from './routes/api/auth/atproto/metadata[.]json'
import { Route as ApiAuthHappyviewCallbackRouteImport } from './routes/api/auth/happyview/callback'
import { Route as AppPPubIdSubscribersIndexRouteImport } from './routes/_app.p.$pubId_.subscribers.index'
import { Route as AppPPubIdSubscribersImportRouteImport } from './routes/_app.p.$pubId_.subscribers.import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiResendWebhookRoute = ApiResendWebhookRouteImport.update({
  id: '/api/resend-webhook',
  path: '/api/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribePubIdRoute = SubscribePubIdRouteImport.update({
  id: '/subscribe/$pubId',
  path: '/subscribe/$pubId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeConfirmRoute = SubscribeConfirmRouteImport.update({
  id: '/subscribe/confirm',
  path: '/subscribe/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeManageRoute = SubscribeManageRouteImport.update({
  id: '/subscribe/manage',
  path: '/subscribe/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeTokenRoute = UnsubscribeTokenRouteImport.update({
  id: '/unsubscribe/$token',
  path: '/unsubscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPPubIdRoute = AppPPubIdRouteImport.update({
  id: '/p/$pubId',
  path: '/p/$pubId',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribersImportRoute = ApiSubscribersImportRouteImport.update({
  id: '/api/subscribers/import',
  path: '/api/subscribers/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionUnsubscribeRoute =
  ApiSubscriptionUnsubscribeRouteImport.update({
    id: '/api/subscription/unsubscribe',
    path: '/api/subscription/unsubscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPPubIdSendPathRoute = AppPPubIdSendPathRouteImport.update({
  id: '/p/$pubId_/$sendPath',
  path: '/p/$pubId/$sendPath',
  getParentRoute: () => AppRoute,
} as any)
const AppPPubIdSettingsRoute = AppPPubIdSettingsRouteImport.update({
  id: '/p/$pubId_/settings',
  path: '/p/$pubId/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthAtprotoAuthorizeRoute = ApiAuthAtprotoAuthorizeRouteImport.update({
  id: '/api/auth/atproto/authorize',
  path: '/api/auth/atproto/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoCallbackRoute = ApiAuthAtprotoCallbackRouteImport.update({
  id: '/api/auth/atproto/callback',
  path: '/api/auth/atproto/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAtprotoJwksDotjsonRoute =
  ApiAuthAtprotoJwksDotjsonRouteImport.update({
    id: '/api/auth/atproto/jwks.json',
    path: '/api/auth/atproto/jwks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthAtprotoMetadataDotjsonRoute =
  ApiAuthAtprotoMetadataDotjsonRouteImport.update({
    id: '/api/auth/atproto/metadata.json',
    path: '/api/auth/atproto/metadata.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthHappyviewCallbackRoute =
  ApiAuthHappyviewCallbackRouteImport.update({
    id: '/api/auth/happyview/callback',
    path: '/api/auth/happyview/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPPubIdSubscribersIndexRoute =
  AppPPubIdSubscribersIndexRouteImport.update({
    id: '/p/$pubId_/subscribers/',
    path: '/p/$pubId/subscribers/',
    getParentRoute: () => AppRoute,
  } as any)
const AppPPubIdSubscribersImportRoute =
  AppPPubIdSubscribersImportRouteImport.update({
    id: '/p/$pubId_/subscribers/import',
    path: '/p/$pubId/subscribers/import',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connect': typeof AppConnectRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/subscribe/$pubId': typeof SubscribePubIdRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/manage': typeof SubscribeManageRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/p/$pubId': typeof AppPPubIdRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/subscribers/import': typeof ApiSubscribersImportRoute
  '/api/subscription/unsubscribe': typeof ApiSubscriptionUnsubscribeRoute
  '/p/$pubId/$sendPath': typeof AppPPubIdSendPathRoute
  '/p/$pubId/settings': typeof AppPPubIdSettingsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/happyview/callback': typeof ApiAuthHappyviewCallbackRoute
  '/p/$pubId/subscribers/import': typeof AppPPubIdSubscribersImportRoute
  '/p/$pubId/subscribers/': typeof AppPPubIdSubscribersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/connect': typeof AppConnectRoute
  '/dashboard': typeof AppDashboardRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/subscribe/$pubId': typeof SubscribePubIdRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/manage': typeof SubscribeManageRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/p/$pubId': typeof AppPPubIdRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/subscribers/import': typeof ApiSubscribersImportRoute
  '/api/subscription/unsubscribe': typeof ApiSubscriptionUnsubscribeRoute
  '/p/$pubId/$sendPath': typeof AppPPubIdSendPathRoute
  '/p/$pubId/settings': typeof AppPPubIdSettingsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/happyview/callback': typeof ApiAuthHappyviewCallbackRoute
  '/p/$pubId/subscribers/import': typeof AppPPubIdSubscribersImportRoute
  '/p/$pubId/subscribers': typeof AppPPubIdSubscribersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/connect': typeof AppConnectRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/api/resend-webhook': typeof ApiResendWebhookRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/subscribe/$pubId': typeof SubscribePubIdRoute
  '/subscribe/confirm': typeof SubscribeConfirmRoute
  '/subscribe/manage': typeof SubscribeManageRoute
  '/unsubscribe/$token': typeof UnsubscribeTokenRoute
  '/_app/p/$pubId': typeof AppPPubIdRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/subscribers/import': typeof ApiSubscribersImportRoute
  '/api/subscription/unsubscribe': typeof ApiSubscriptionUnsubscribeRoute
  '/_app/p/$pubId_/$sendPath': typeof AppPPubIdSendPathRoute
  '/_app/p/$pubId_/settings': typeof AppPPubIdSettingsRoute
  '/api/auth/atproto/authorize': typeof ApiAuthAtprotoAuthorizeRoute
  '/api/auth/atproto/callback': typeof ApiAuthAtprotoCallbackRoute
  '/api/auth/atproto/jwks.json': typeof ApiAuthAtprotoJwksDotjsonRoute
  '/api/auth/atproto/metadata.json': typeof ApiAuthAtprotoMetadataDotjsonRoute
  '/api/auth/happyview/callback': typeof ApiAuthHappyviewCallbackRoute
  '/_app/p/$pubId_/subscribers/import': typeof AppPPubIdSubscribersImportRoute
  '/_app/p/$pubId_/subscribers/': typeof AppPPubIdSubscribersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connect'
    | '/dashboard'
    | '/api/resend-webhook'
    | '/api/subscribe'
    | '/subscribe/$pubId'
    | '/subscribe/confirm'
    | '/subscribe/manage'
    | '/unsubscribe/$token'
    | '/p/$pubId'
    | '/api/auth/logout'
    | '/api/subscribers/import'
    | '/api/subscription/unsubscribe'
    | '/p/$pubId/$sendPath'
    | '/p/$pubId/settings'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/happyview/callback'
    | '/p/$pubId/subscribers/import'
    | '/p/$pubId/subscribers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/connect'
    | '/dashboard'
    | '/api/resend-webhook'
    | '/api/subscribe'
    | '/subscribe/$pubId'
    | '/subscribe/confirm'
    | '/subscribe/manage'
    | '/unsubscribe/$token'
    | '/p/$pubId'
    | '/api/auth/logout'
    | '/api/subscribers/import'
    | '/api/subscription/unsubscribe'
    | '/p/$pubId/$sendPath'
    | '/p/$pubId/settings'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/happyview/callback'
    | '/p/$pubId/subscribers/import'
    | '/p/$pubId/subscribers'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/connect'
    | '/_app/dashboard'
    | '/api/resend-webhook'
    | '/api/subscribe'
    | '/subscribe/$pubId'
    | '/subscribe/confirm'
    | '/subscribe/manage'
    | '/unsubscribe/$token'
    | '/_app/p/$pubId'
    | '/api/auth/logout'
    | '/api/subscribers/import'
    | '/api/subscription/unsubscribe'
    | '/_app/p/$pubId_/$sendPath'
    | '/_app/p/$pubId_/settings'
    | '/api/auth/atproto/authorize'
    | '/api/auth/atproto/callback'
    | '/api/auth/atproto/jwks.json'
    | '/api/auth/atproto/metadata.json'
    | '/api/auth/happyview/callback'
    | '/_app/p/$pubId_/subscribers/import'
    | '/_app/p/$pubId_/subscribers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiResendWebhookRoute: typeof ApiResendWebhookRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  SubscribePubIdRoute: typeof SubscribePubIdRoute
  SubscribeConfirmRoute: typeof SubscribeConfirmRoute
  SubscribeManageRoute: typeof SubscribeManageRoute
  UnsubscribeTokenRoute: typeof UnsubscribeTokenRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiSubscribersImportRoute: typeof ApiSubscribersImportRoute
  ApiSubscriptionUnsubscribeRoute: typeof ApiSubscriptionUnsubscribeRoute
  ApiAuthAtprotoAuthorizeRoute: typeof ApiAuthAtprotoAuthorizeRoute
  ApiAuthAtprotoCallbackRoute: typeof ApiAuthAtprotoCallbackRoute
  ApiAuthAtprotoJwksDotjsonRoute: typeof ApiAuthAtprotoJwksDotjsonRoute
  ApiAuthAtprotoMetadataDotjsonRoute: typeof ApiAuthAtprotoMetadataDotjsonRoute
  ApiAuthHappyviewCallbackRoute: typeof ApiAuthHappyviewCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/resend-webhook': {
      id: '/api/resend-webhook'
      path: '/api/resend-webhook'
      fullPath: '/api/resend-webhook'
      preLoaderRoute: typeof ApiResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/$pubId': {
      id: '/subscribe/$pubId'
      path: '/subscribe/$pubId'
      fullPath: '/subscribe/$pubId'
      preLoaderRoute: typeof SubscribePubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/confirm': {
      id: '/subscribe/confirm'
      path: '/subscribe/confirm'
      fullPath: '/subscribe/confirm'
      preLoaderRoute: typeof SubscribeConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/manage': {
      id: '/subscribe/manage'
      path: '/subscribe/manage'
      fullPath: '/subscribe/manage'
      preLoaderRoute: typeof SubscribeManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe/$token': {
      id: '/unsubscribe/$token'
      path: '/unsubscribe/$token'
      fullPath: '/unsubscribe/$token'
      preLoaderRoute: typeof UnsubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$pubId': {
      id: '/_app/p/$pubId'
      path: '/p/$pubId'
      fullPath: '/p/$pubId'
      preLoaderRoute: typeof AppPPubIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribers/import': {
      id: '/api/subscribers/import'
      path: '/api/subscribers/import'
      fullPath: '/api/subscribers/import'
      preLoaderRoute: typeof ApiSubscribersImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/unsubscribe': {
      id: '/api/subscription/unsubscribe'
      path: '/api/subscription/unsubscribe'
      fullPath: '/api/subscription/unsubscribe'
      preLoaderRoute: typeof ApiSubscriptionUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$pubId_/$sendPath': {
      id: '/_app/p/$pubId_/$sendPath'
      path: '/p/$pubId/$sendPath'
      fullPath: '/p/$pubId/$sendPath'
      preLoaderRoute: typeof AppPPubIdSendPathRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$pubId_/settings': {
      id: '/_app/p/$pubId_/settings'
      path: '/p/$pubId/settings'
      fullPath: '/p/$pubId/settings'
      preLoaderRoute: typeof AppPPubIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/atproto/authorize': {
      id: '/api/auth/atproto/authorize'
      path: '/api/auth/atproto/authorize'
      fullPath: '/api/auth/atproto/authorize'
      preLoaderRoute: typeof ApiAuthAtprotoAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/callback': {
      id: '/api/auth/atproto/callback'
      path: '/api/auth/atproto/callback'
      fullPath: '/api/auth/atproto/callback'
      preLoaderRoute: typeof ApiAuthAtprotoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/jwks.json': {
      id: '/api/auth/atproto/jwks.json'
      path: '/api/auth/atproto/jwks.json'
      fullPath: '/api/auth/atproto/jwks.json'
      preLoaderRoute: typeof ApiAuthAtprotoJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/atproto/metadata.json': {
      id: '/api/auth/atproto/metadata.json'
      path: '/api/auth/atproto/metadata.json'
      fullPath: '/api/auth/atproto/metadata.json'
      preLoaderRoute: typeof ApiAuthAtprotoMetadataDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/happyview/callback': {
      id: '/api/auth/happyview/callback'
      path: '/api/auth/happyview/callback'
      fullPath: '/api/auth/happyview/callback'
      preLoaderRoute: typeof ApiAuthHappyviewCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$pubId_/subscribers/': {
      id: '/_app/p/$pubId_/subscribers/'
      path: '/p/$pubId/subscribers'
      fullPath: '/p/$pubId/subscribers/'
      preLoaderRoute: typeof AppPPubIdSubscribersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$pubId_/subscribers/import': {
      id: '/_app/p/$pubId_/subscribers/import'
      path: '/p/$pubId/subscribers/import'
      fullPath: '/p/$pubId/subscribers/import'
      preLoaderRoute: typeof AppPPubIdSubscribersImportRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPPubIdRoute: typeof AppPPubIdRoute
  AppPPubIdSendPathRoute: typeof AppPPubIdSendPathRoute
  AppPPubIdSettingsRoute: typeof AppPPubIdSettingsRoute
  AppPPubIdSubscribersImportRoute: typeof AppPPubIdSubscribersImportRoute
  AppPPubIdSubscribersIndexRoute: typeof AppPPubIdSubscribersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPPubIdRoute: AppPPubIdRoute,
  AppPPubIdSendPathRoute: AppPPubIdSendPathRoute,
  AppPPubIdSettingsRoute: AppPPubIdSettingsRoute,
  AppPPubIdSubscribersImportRoute: AppPPubIdSubscribersImportRoute,
  AppPPubIdSubscribersIndexRoute: AppPPubIdSubscribersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiResendWebhookRoute: ApiResendWebhookRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  SubscribePubIdRoute: SubscribePubIdRoute,
  SubscribeConfirmRoute: SubscribeConfirmRoute,
  SubscribeManageRoute: SubscribeManageRoute,
  UnsubscribeTokenRoute: UnsubscribeTokenRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiSubscribersImportRoute: ApiSubscribersImportRoute,
  ApiSubscriptionUnsubscribeRoute: ApiSubscriptionUnsubscribeRoute,
  ApiAuthAtprotoAuthorizeRoute: ApiAuthAtprotoAuthorizeRoute,
  ApiAuthAtprotoCallbackRoute: ApiAuthAtprotoCallbackRoute,
  ApiAuthAtprotoJwksDotjsonRoute: ApiAuthAtprotoJwksDotjsonRoute,
  ApiAuthAtprotoMetadataDotjsonRoute: ApiAuthAtprotoMetadataDotjsonRoute,
  ApiAuthHappyviewCallbackRoute: ApiAuthHappyviewCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
